import React from 'react';
// import logo from './logo.svg';
import './App.css';
import ReportComponent from './components/report/report';

const App = () => {
  const tblReportId = '232d9ad2-24ff-4947-aaac-2443fdeb7322';

  const tblReportEmbedUrl = `https://app.powerbi.com/reportEmbed?reportId=${tblReportId}&config=eyJjbHVzdGVyVXJsIjoiaHR0cHM6Ly9XQUJJLVVTLU5PUlRILUNFTlRSQUwtRy1QUklNQVJZLXJlZGlyZWN0LmFuYWx5c2lzLndpbmRvd3MubmV0IiwiZW1iZWRGZWF0dXJlcyI6eyJtb2Rlcm5FbWJlZCI6dHJ1ZSwidXNhZ2VNZXRyaWNzVk5leHQiOnRydWUsImRpc2FibGVBbmd1bGFySlNCb290c3RyYXBSZGxFbWJlZCI6dHJ1ZX19`;

 const areaChartReportId = 'f2774993-8d1a-4034-9c02-feca7bd5d8be';
 const areaChartReportEmbedUrl = `https://app.powerbi.com/reportEmbed?reportId=${areaChartReportId}&config=eyJjbHVzdGVyVXJsIjoiaHR0cHM6Ly9XQUJJLVVTLU5PUlRILUNFTlRSQUwtRy1QUklNQVJZLXJlZGlyZWN0LmFuYWx5c2lzLndpbmRvd3MubmV0IiwiZW1iZWRGZWF0dXJlcyI6eyJtb2Rlcm5FbWJlZCI6dHJ1ZSwidXNhZ2VNZXRyaWNzVk5leHQiOnRydWV9fQ%3d%3d`;

  const embedToken = `eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyIsImtpZCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyJ9.eyJhdWQiOiJodHRwczovL2FuYWx5c2lzLndpbmRvd3MubmV0L3Bvd2VyYmkvYXBpIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvZDQ3MGJmN2QtM2RiYS00MjE2LWE4MWEtMTE2MDg3MWVhYjY0LyIsImlhdCI6MTY5NTM3ODg2MCwibmJmIjoxNjk1Mzc4ODYwLCJleHAiOjE2OTUzODM0NzcsImFjY3QiOjAsImFjciI6IjEiLCJhaW8iOiJBVlFBcS84VUFBQUFEMkNKNVkzS2dSQ2lWNWR0RVpCUDNDcStha2luTkZsVHZVZXhxSHhQYTlObE1OQnVpdDVqUk51ZXpjZVBqU2xkLzhTc25KNVFBTURkN3A3YzRTT1ZNREV2SE5vanlMb3VZTkpCVWg3YkxxWT0iLCJhbXIiOlsicHdkIiwibWZhIl0sImFwcGlkIjoiODcxYzAxMGYtNWU2MS00ZmIxLTgzYWMtOTg2MTBhN2U5MTEwIiwiYXBwaWRhY3IiOiIwIiwiaXBhZGRyIjoiMTEwLjkzLjIzNy4xMDUiLCJuYW1lIjoiS2FyYWNoaS1QQklwcm8iLCJvaWQiOiIzZTllN2VkZC0xNDljLTRmMDMtOGY4ZS1hOWFmNTA5ODIwZWEiLCJvbnByZW1fc2lkIjoiUy0xLTUtMjEtNTY3Mjk5OTkwLTM4NDk1OTIyMjItMTAxNjQ0ODgzOS0yMDIwIiwicHVpZCI6IjEwMDMyMDAyODlBQjg5MkEiLCJyaCI6IjAuQVN3QWZiOXcxTG85RmtLb0doRmdoeDZyWkFrQUFBQUFBQUFBd0FBQUFBQUFBQUFzQUF3LiIsInNjcCI6InVzZXJfaW1wZXJzb25hdGlvbiIsInN1YiI6Ijc3eWNtMmJOM2xzakV0eFY1OGZuU05PU0F0bTJ5WnVfdTd3Ujc0WWFTZTAiLCJ0aWQiOiJkNDcwYmY3ZC0zZGJhLTQyMTYtYTgxYS0xMTYwODcxZWFiNjQiLCJ1bmlxdWVfbmFtZSI6IkthcmFjaGktUEJJcHJvQGdldGFjdmlkZW81NTQzMS5vbm1pY3Jvc29mdC5jb20iLCJ1cG4iOiJLYXJhY2hpLVBCSXByb0BnZXRhY3ZpZGVvNTU0MzEub25taWNyb3NvZnQuY29tIiwidXRpIjoiN2pMcDRsZkpUMC03bU9SRTQ2a1pBQSIsInZlciI6IjEuMCIsIndpZHMiOlsiYjc5ZmJmNGQtM2VmOS00Njg5LTgxNDMtNzZiMTk0ZTg1NTA5Il19.ZOHXbh23iAMbKeSQxrGttCTqfL8Sp5otv2pYUl6AXUMpB3CtSGP8H-O_1a9VXJUU9Y5eK8Bz1TEr3QCpW1GCYfu_hdZTIWFBuWdCmchE9KWKkdyIABd6cPOjnpWsMtxrjC8-GLrHP5h7lYIvsKT7LRn3slwBLmSU_9o388CVfmlmq6pwWXOqnE7Rxeb1q2cfTWtoaURrWTux9StDlNKC6ZHwAbjIZAyO6xPVTyfBBe_M6QqSaoBx6NGwOIYn1HrukYXn8w8j_pgHsKDlLBzzEFJIG9NGbEdHBwOQqujwZRbygi7G8eJFMgEg4mbQPy0TxygHtD7K6Ag_drdxyUnZ2w`;
  //NOTE: Copy token from PowerBI interface using command 'copy(powerBIAccessToken)'.


  const areaChartOneReportId = 'fadf9640-5c43-4076-8190-9a01e706a032';
  const areaChartOneReportEmbedUrl = `https://app.powerbi.com/reportEmbed?reportId=${areaChartOneReportId}&      config=eyJjbHVzdGVyVXJsIjoiaHR0cHM6Ly9XQUJJLVVTLU5PUlRILUNFTlRSQUwtRy1QUklNQVJZLXJlZGlyZWN0LmFuYWx5c2lzLndpbmRvd3MubmV0IiwiZW1iZWRGZWF0dXJlcyI6eyJ1c2FnZU1ldHJpY3NWTmV4dCI6dHJ1ZX19`;

  return (
    <div className="App">
      {/* <ReportComponent reportId={tblReportId} embedUrl={tblReportEmbedUrl} embedToken={embedToken} /> */}
      {/* <ReportComponent reportId={areaChartReportId} embedUrl={areaChartReportEmbedUrl} embedToken={embedToken} /> */}
      <ReportComponent reportId={areaChartOneReportEmbedUrl} embedUrl={areaChartOneReportEmbedUrl} embedToken={""} />
    </div>
  );
}

export default App;
