import React from 'react';
// import logo from './logo.svg';
import './App.css';
import ReportComponent from './components/report/report';

const App = () => {
  const tblReportId = '4ac1d6a4-9991-4b0b-9e73-ad2faed5b474';
  const tblReportEmbedUrl = `https://app.powerbi.com/reportEmbed?reportId=${tblReportId}&config=eyJjbHVzdGVyVXJsIjoiaHR0cHM6Ly9XQUJJLVVTLU5PUlRILUNFTlRSQUwtRy1QUklNQVJZLXJlZGlyZWN0LmFuYWx5c2lzLndpbmRvd3MubmV0IiwiZW1iZWRGZWF0dXJlcyI6eyJtb2Rlcm5FbWJlZCI6dHJ1ZSwidXNhZ2VNZXRyaWNzVk5leHQiOnRydWV9fQ%3d%3d`;


 const areaChartReportId = 'f2774993-8d1a-4034-9c02-feca7bd5d8be';
 const areaChartReportEmbedUrl = `https://app.powerbi.com/reportEmbed?reportId=${areaChartReportId}&config=eyJjbHVzdGVyVXJsIjoiaHR0cHM6Ly9XQUJJLVVTLU5PUlRILUNFTlRSQUwtRy1QUklNQVJZLXJlZGlyZWN0LmFuYWx5c2lzLndpbmRvd3MubmV0IiwiZW1iZWRGZWF0dXJlcyI6eyJtb2Rlcm5FbWJlZCI6dHJ1ZSwidXNhZ2VNZXRyaWNzVk5leHQiOnRydWV9fQ%3d%3d`;

  const embedToken = `eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyIsImtpZCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyJ9.eyJhdWQiOiJodHRwczovL2FuYWx5c2lzLndpbmRvd3MubmV0L3Bvd2VyYmkvYXBpIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvZDQ3MGJmN2QtM2RiYS00MjE2LWE4MWEtMTE2MDg3MWVhYjY0LyIsImlhdCI6MTY4NDQ5NTI1NiwibmJmIjoxNjg0NDk1MjU2LCJleHAiOjE2ODQ1MDAzODUsImFjY3QiOjAsImFjciI6IjEiLCJhaW8iOiJBVlFBcS84VEFBQUFoTWF0ZlM3Q2dVNStYUEZGSTE2VTFHOUExd1MxYTlWNVdEZWRuUUtUalI0ZTNiZ0ROUHFHRk1acUZPVmVyV3VqMlhVYjNyYnVVRERKZ2cxZUo1VjV4cVpTY21yK0xlUlAzSnhMMTVtcURDND0iLCJhbXIiOlsicHdkIiwibWZhIl0sImFwcGlkIjoiODcxYzAxMGYtNWU2MS00ZmIxLTgzYWMtOTg2MTBhN2U5MTEwIiwiYXBwaWRhY3IiOiIyIiwiaXBhZGRyIjoiNTguNjUuMTk4LjIwOSIsIm5hbWUiOiJLYXJhY2hpLVBCSXBybyIsIm9pZCI6IjNlOWU3ZWRkLTE0OWMtNGYwMy04ZjhlLWE5YWY1MDk4MjBlYSIsIm9ucHJlbV9zaWQiOiJTLTEtNS0yMS01NjcyOTk5OTAtMzg0OTU5MjIyMi0xMDE2NDQ4ODM5LTIwMjAiLCJwdWlkIjoiMTAwMzIwMDI4OUFCODkyQSIsInJoIjoiMC5BU3dBZmI5dzFMbzlGa0tvR2hGZ2h4NnJaQWtBQUFBQUFBQUF3QUFBQUFBQUFBQXNBQXcuIiwic2NwIjoidXNlcl9pbXBlcnNvbmF0aW9uIiwic2lnbmluX3N0YXRlIjpbImttc2kiXSwic3ViIjoiNzd5Y20yYk4zbHNqRXR4VjU4Zm5TTk9TQXRtMnladV91N3dSNzRZYVNlMCIsInRpZCI6ImQ0NzBiZjdkLTNkYmEtNDIxNi1hODFhLTExNjA4NzFlYWI2NCIsInVuaXF1ZV9uYW1lIjoiS2FyYWNoaS1QQklwcm9AZ2V0YWN2aWRlbzU1NDMxLm9ubWljcm9zb2Z0LmNvbSIsInVwbiI6IkthcmFjaGktUEJJcHJvQGdldGFjdmlkZW81NTQzMS5vbm1pY3Jvc29mdC5jb20iLCJ1dGkiOiJqZkRzdkhCajJFcXBTUzhXaHFJSEFBIiwidmVyIjoiMS4wIiwid2lkcyI6WyJiNzlmYmY0ZC0zZWY5LTQ2ODktODE0My03NmIxOTRlODU1MDkiXX0.QbOdkYhWH0s6Cw_xl5TrShCRX8mOxUxmcTf556MyvLrEuJ4DaV_EaQIPIpVcx_72bT6ycCwIx6nl1u0p8r5tZF8DKuN4y9azHhtDqNbeL2GVxpKVcohKPZCgoQ-uj4fgQmJVnpoPj7dhrbgrhx3bca1m5c03Xydol7Hl-3TuliwGslRht8d1v0U7LfZ8bbWJRkLkmVNavHK20WAGMJdLJ9gF8N-zVq4eG7iQr9L0fPrtQ7ggQMN2XiFbgaV05ECICQbRIO23dKcAZniwtZ_QWFq93m1BFT5rpATJNeE1SvpcCLqUoGjsrw_mzkibHCpWpOLHDVx4K2DpPwLie5RKDw`;
  //NOTE: Copy token from PowerBI interface using command 'copy(powerBIAccessToken)'.

  return (
    <div className="App">
      <ReportComponent reportId={tblReportId} embedUrl={tblReportEmbedUrl} embedToken={embedToken} />
      <ReportComponent reportId={areaChartReportId} embedUrl={areaChartReportEmbedUrl} embedToken={embedToken} />
    </div>
  );
}

export default App;
